# Generated by Django 4.1.2 on 2022-10-25 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
